theme: jekyll-theme-hacker
title: tldr pages Browser Extension 
description: Collaborative cheatsheets for console commands (tldr project) now in your Browser! Available for Chrome, Edge, Firefox and other Chromium based browsers.
