name: Generate artifacts to publish

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run process-styles
      - run: npm run js-minify
      - run: rm -rf node_modules
      - run: npm install --production
      - run: rm -rf assets && rm -rf .github && rm -rf .git && rm .gitignore package-lock.json package.json part.edge.json part.firefox.json CHANGELOG.md styles/main.css styles/main.css.map styles/main.scss styles/popup.css styles/popup.css.map styles/popup.scss
      - run: find ./node_modules/ ! \( -name "node_modules" -or -name "marked" \) -type d -exec rm -rf {} +
      - run: find ./node_modules ! -name 'marked.min.js' -type f -exec rm -f {} +
      - uses: actions/upload-artifact@v2
        with:
          name: tldr-pages-chrome
          path: .

  firefox:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run process-styles
      - run: npm run js-minify
      - run: rm -rf node_modules
      - run: npm install --production
      - run: echo $(jq 'del(.background)' manifest.json) > manifest.json
      - run: echo $(jq 'del(.action)' manifest.json) > manifest.json
      - run: echo $(jq -s 'reduce .[] as $item ({}; . * $item)' manifest.json part.firefox.json) > manifest.json
      - run: rm -rf assets && rm -rf .github && rm -rf .git && rm .gitignore package-lock.json package.json part.edge.json part.firefox.json CHANGELOG.md styles/main.css styles/main.css.map styles/main.scss styles/popup.css styles/popup.css.map styles/popup.scss
      - run: find ./node_modules/ ! \( -name "node_modules" -or -name "marked" \) -type d -exec rm -rf {} +
      - run: find ./node_modules ! -name 'marked.min.js' -type f -exec rm -f {} +
      - uses: actions/upload-artifact@v2
        with:
          name: tldr-pages-firefox
          path: .

  edge:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run process-styles
      - run: npm run js-minify
      - run: rm -rf node_modules
      - run: npm install --production
      - run: echo $(jq -s 'reduce .[] as $item ({}; . * $item)' manifest.json part.edge.json) > manifest.json
      - run: rm -rf assets && rm -rf .github && rm -rf .git && rm .gitignore package-lock.json package.json part.edge.json part.firefox.json CHANGELOG.md styles/main.css styles/main.css.map styles/main.scss styles/popup.css styles/popup.css.map styles/popup.scss
      - run: find ./node_modules/ ! \( -name "node_modules" -or -name "marked" \) -type d -exec rm -rf {} +
      - run: find ./node_modules ! -name 'marked.min.js' -type f -exec rm -f {} +
      - uses: actions/upload-artifact@v2
        with:
          name: tldr-pages-edge
          path: .