name: Generate artifacts to publish

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: |
          chmod +x ./scripts/generateChromeExtension.sh
          ./scripts/generateChromeExtension.sh
      - uses: actions/upload-artifact@v2
        with:
          name: tldr-pages-chrome
          path: tldr-pages-chrome.zip

  firefox:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: |
          chmod +x ./scripts/generateFirefoxExtension.sh
          ./scripts/generateFirefoxExtension.sh
      - uses: actions/upload-artifact@v2
        with:
          name: tldr-pages-firefox
          path: tldr-pages-firefox.xpi

  edge:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: |
          chmod +x ./scripts/generateEdgeExtension.sh
          ./scripts/generateEdgeExtension.sh
      - uses: actions/upload-artifact@v2
        with:
          name: tldr-pages-edge
          path: tldr-pages-edge.zip